"""printed bank details

Revision ID: 77fc68474636
Revises: 3d2aa2394ae9
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77fc68474636'
down_revision: Union[str, None] = '3d2aa2394ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('bank_details', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'bank_details')
    # ### end Alembic commands ###
